apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: concourse-ing-traefik
  namespace: concourse
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - host: TODO
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: concourse-web
                port:
                  number: 8080
