---
- name: bootstrap to {{ my_host }}
  hosts: localhost
  gather_facts: no

  tasks:
    - name: add target host
      ansible.builtin.add_host:
        hostname: "{{ my_host }}"
        ansible_ssh_host: "{{ my_host }}"
        ansible_become_method: doas

- name: woodpecker configuration
  hosts: all
  gather_facts: no

  tasks:
    - name: add secrets
      block:
        - name: get woodpecker-cli version
          ansible.builtin.raw: wget -q "https://api.github.com/repos/woodpecker-ci/woodpecker/releases/latest" -O- | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | awk '{print(substr($1,2))}'
          register: wp_version

        - name: "download woodpecker-cli v{{ wp_version.stdout.splitlines()[0] }}"
          ansible.builtin.raw: |
            rm -rf /tmp/wp
            mkdir -p /tmp/wp;
            wget https://github.com/woodpecker-ci/woodpecker/releases/download/v{{ wp_version.stdout.splitlines()[0] }}/woodpecker-cli-{{ wp_version.stdout.splitlines()[0] }}.x86_64.rpm -O /tmp/wp/wp.rpm

        - name: install rpm2cpio
          become: true
          ansible.builtin.raw: apk add --no-cache rpm2cpio

        - name: extract archive
          ansible.builtin.raw: |
            cd /tmp/wp;
            rpm2cpio wp.rpm | cpio -idmv
            rm wp.rpm

        - name: remove rpm2cpio
          become: true
          ansible.builtin.raw: apk del --purge rpm2cpio

        - name: set path fact
          set_fact:
            wp_cli: "/tmp/wp/usr/local/bin/woodpecker"

        - name: set event fact
          set_fact:
            events: "cron,deployment,manual,push,tag"

        - name: add secrets
          ansible.builtin.raw: |
            export WOODPECKER_SERVER="https://{{ wood_cr }}";
            export WOODPECKER_TOKEN="{{ wood_token }}";
            {{ wp_cli }} secret rm --global -name ci_registry | cat 2>/dev/null;
            {{ wp_cli }} secret rm --global -name docker_username | cat 2>/dev/null;
            {{ wp_cli }} secret rm --global -name docker_password | cat 2>/dev/null;
            {{ wp_cli }} secret add --global --event="{{ events }}" -name ci_registry -value {{ wood_cr }};
            {{ wp_cli }} secret add --global --event="{{ events }}" -name docker_username -value {{ wood_du }};
            {{ wp_cli }} secret add --global --event="{{ events }}" -name docker_password -value {{ wood_dp }};

        - name: cleanup
          ansible.builtin.raw: rm -rf /tmp/wp
